// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['api']['App']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['api']['App']['Get'](arg1);
}

export function List(arg1) {
  return window['go']['api']['App']['List'](arg1);
}

export function LoadSettings(arg1) {
  return window['go']['api']['App']['LoadSettings'](arg1);
}

export function ParseUrl(arg1) {
  return window['go']['api']['App']['ParseUrl'](arg1);
}

export function Pause(arg1) {
  return window['go']['api']['App']['Pause'](arg1);
}

export function Resume(arg1) {
  return window['go']['api']['App']['Resume'](arg1);
}

export function Save(arg1) {
  return window['go']['api']['App']['Save'](arg1);
}

export function SettingUpdate(arg1) {
  return window['go']['api']['App']['SettingUpdate'](arg1);
}
