// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1:string):Promise<string>;

export function Get(arg1:string):Promise<string>;

export function List(arg1:string):Promise<string>;

export function LoadSettings(arg1:string):Promise<string>;

export function ParseUrl(arg1:string):Promise<string>;

export function Pause(arg1:string):Promise<string>;

export function Resume(arg1:string):Promise<string>;

export function Save(arg1:string):Promise<string>;

export function SettingUpdate(arg1:string):Promise<string>;
